import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from "next/font/google";
import './globals.scss';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: 'Telegram Web',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased text-color-text select-none">
        {children}
      </body>
    </html>
  );
}
